### ISSUE TITLE
Allow for usage of checkbox menu item in contextMenu.add() function

### ISSUE THREAD

**Issue by Controlfreak707** [GooseMod/Injector#13]
I've been poking around with context menus and `MenuItem` is used for most things. The only time I found that `MenuItem` was not being used was with checkbox menu items, which I just so happened to be needing at the time (for the [Toggle Message Buttons module](https://github.com/GooseMod/Modules/pull/25)). **The point is, I would like to be able to use `MenuItemCheckbox`s with the `goosemod.patcher.contextMenu.add()` function.**

I don't believe it would be too difficult to implement, but if it is, then I understand if you decide not to work on this anytime soon.

Thank you for your time, have a great day!

(Side-note: why does Discord use the same thing for all the context menus *except when it comes to checkboxes? **They even use `MenuItem` for sliders!***)

**Comment by CanadaHonk** [comment]
Done in recent commit.
