### ISSUE TITLE
[Patcher APIs] The ability to disclude buttons from certain text fields in patcher.channelTextAreaButtons

### ISSUE THREAD

**Issue by Controlfreak707** [GooseMod/Injector#18]
The ability to disclude buttons from certain text fields such as channels the user cannot speak in and the upload modal.
Using the function should look something like this, obviously with shorter parameter names:
```js
...channelTextAreaButtons.patch(tooltipText, imgSrc, clickHandler, includeForbiddenChannels = true, includeUpload = true)
```
This came to my mind because I'm working on a "Send Button" module and I don't want the button to appear in channels that are forbidden.

**Comment by CanadaHonk** [comment]
This will probably be added in a future release (likely v6.1.0).

**Comment by CanadaHonk** [comment]
Added in last commit.
