### ISSUE TITLE
[Bug] "DOM" tag basically completely breaks the module store

### ISSUE THREAD

**Issue by Controlfreak707** [GooseMod/Injector#29]
**Describe the bug**
Selecting the "DOM" tag in the module store shows no modules, despite the number 64 being displayed to the right of it. Upon unselecting, only "i fixed discord" module appears. At this point, selecting other tags leads to no modules being shown.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to "User Settings"
2. Click on "Module Store"
3. Select "DOM" tag
4. See unexpected behaviour
5. Unselect "DOM" tag
6. See unexpected behaviour

**Expected behaviour**
I expect to see modules tagged with "DOM" upon selecting the tag, and I expect to see all modules when I unselect the tag.

**Screenshots**
##### Before selecting "DOM" tag
![image](https://user-images.githubusercontent.com/35977727/108139830-c136a300-7075-11eb-9d27-40f3442be929.png)

##### After selecting "DOM" tag
![image](https://user-images.githubusercontent.com/35977727/108140051-2a1e1b00-7076-11eb-88b8-2198bac4db67.png)

##### After unselecting "DOM" tag
![image](https://user-images.githubusercontent.com/35977727/108140140-56399c00-7076-11eb-958c-79d36b80a2ca.png)

**GooseMod info:**
 - Update Channel: Release
 - Version: 7.0.0 (3163331)
 - Modules: Better Animations, Better Message Deletion, Better NSFW, Copy Raw, Dev Mode, Fucklytics, Hardcoded Color Fixer, Nicer User Connections, Relaunch, Show All Activities, Visual Tweaks, Webhook Tags

**Discord info:**
 - Update Channel: Stable
 - OS:
     - Acording to Discord: Linux 64-Bit (5.10.15-200.Fc33.X86_64)
     - Acording to my computer: Fedora 33 (Workstation Edition)
 - Host Version: 0.0.13
 - Web Version: Stable 76771 (f5e89dd)

**Additional context**
I recently switched from the dev branch back to the release branch.

**Comment by caughtquick** [comment]
adding on to this the react tabs has the same issue

**Comment by CanadaHonk** [comment]
Bug in MS2Builder more likely, investigating.

**Comment by CanadaHonk** [comment]
The bug likely isn't in Injector and isn't related to new tags.

**Comment by CanadaHonk** [comment]
Ignore above, turns out it is a hidden bug in Injector.

**Comment by CanadaHonk** [comment]
Fixed for v7.1.0, also temporarily fixed via a different method MS2Builder side.
